### ISSUE TITLE
starting app

### ISSUE THREAD

**Issue by asebak** [mtpereira/ansible-nodejs-app#2]
Everything works fine but at the end I get

TASK: [nodejs | deploy - start app] ******************************************\* 
msg: start: Unknown job: app-name

Do you know what the problem can be, I am not using nodesource, I have a ansible task that installs nodejs so I don't know if that could be causing the problem

**Comment by mtpereira** [comment]
Hello,

So, `nodejs_app_name` is set to `app-name`, right?

The issue seems to be that, for some reason, upstart is not finding our init file. Please check if `/etc/init/app-name.conf` exists and check if its contents make sense.

**Comment by asebak** [comment]
@mtpereira yes the file exists and it contains the following content and it is the app-name=sample-ui

# Managed by Ansible, do not edit!

start on runlevel [2345]
stop on runlevel [!2345]

setuid nodejs
setgid nodejs

script
  . /etc/default/sample-ui
  chdir /opt/testutilities/nodejs/sample-ui
  echo $$ > /opt/testutilities/nodejs/sample-ui.pid
  exec node server.js
end script

**Comment by mtpereira** [comment]
Well, that's very weird then, because, as you can check in https://github.com/mtpereira/ansible-nodejs-app/blob/master/tasks/deploy.yml , the same `nodejs_app_name` variable is used both for the init script file name and the service start, so it should never complain that the file doesn't exist. 

Also, the init file should be named `sample-ui` and not `app-name`, since that's the value that you've passed to that value and that's the value that was used for generating the init file contents.

Can't this be result of a previous run? Are you somehow executing the role twice with different values?

If you'd like, you can share the playbook and vars you're using so I can try to help you debug it.

**Comment by asebak** [comment]
@mtpereira that was just for an example, can you send me your email I can share with you my source files.

**Comment by asebak** [comment]
@mtpereira okay i figured it out, I am using the init.d instead of the init, thanks for the help
